# Generated by Django 4.0.4 on 2022-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='for_user',
            field=models.CharField(default='Public', max_length=200),
        ),
    ]
