# Generated by Django 4.0.4 on 2022-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user_type',
            field=models.CharField(default='Student', max_length=300),
        ),
    ]
