# Generated by Django 4.0.4 on 2022-05-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritenews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.mainuser'),
        ),
    ]
